### ISSUE TITLE
sapstartsrv is going [defunc] after sap_host_exporter is active

### ISSUE THREAD

**Issue by pirat013** [SUSE/sap_host_exporter#31]
Hi,

I experience massive impact on my 3 node cluster running 5 SAP SID's. If all exporters are active before the SAP systems are running the sapstartsrv will go in defunct and this blocks all other start procedures of the cluster. 
I was able to to reproduce that with stop sap_host_exporter. That looks for me that we have an issue with the sapstartsrv in case to many request are happen.
First of all I'll get in touch with SAP to verify the situation. Second we may should thing if we reduce the data which we are collecting or using a different method. Maybe the socket direct instead of a http request.

**Comment by stefanotorresi** [comment]
Just to keep track of developments about this:

This is 99.9% an upstream issue: some SAPControl methods will cause the start service to crash, especially if they return a 500 response.
The problem is very difficult to reproduce, it most probably involves some internal race condition, and it replicates in many different environments, with or without the suse-cluster-connector involved.

#36 partly works around this issue, and implementing #22 should completely avoid it.
