### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by pipinstallyogi** [SUSE/sap_host_exporter#46]
Hallo all,

When I am trying to run the command " ./sap_host_exporter --sap-control-url http://xx.xx.xx.xx" 
I am getting the following error.

INFO[0000] Could not discover configuration file: Config File "sap_host_exporter" Not Found in "[/root/go/bin /root/.config /etc /usr/etc]"
INFO[0000] Default configuration values will be used
FATA[0000] SAPControl web service error: could not performGetInstanceProperties query: Post http://18.195.2.92: dial tcp 18.195.2.92:80: connect: connection refused

Can someone please guide onto this.
Thanks in advance

**Comment by stefanotorresi** [comment]
Hello @pipinstallyogi,

Since you have not specified any port in the url, port 80 will be used by default, but SAPControl doesn't listen on that, it listens in port `5{instance_number}13`, e.g. 50013 if the instance number is `00`. 

Please, refer to the [official SAP docs](https://www.sap.com/documents/2016/09/0a40e60d-8b7c-0010-82c7-eda71af511fa.html) for further details on SAPControl. :wink:

**Comment by pipinstallyogi** [comment]
Hi @stefanotorresi,

Many Thanks for the reply. You solution worked like a charm.
It is running now.
Best.
